# Site settings
# Site attributes can be referred to, e.g. {{ site.title }}, {{ site.email }}.
# You can create any custom variable myvariable, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Auto Doc Site
description: >- # this means to ignore newlines until "baseurl:"
  This site automagically converts markdowns or asciidoc into html.
  This will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: "" # your-email@example.com
left-footer: "Let it be..."

# Build settings
theme: just-the-docs
source: docs
plugins:
  - jekyll-asciidoc
  - jekyll-optional-front-matter
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-spaceship

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

kramdown:
  syntax_highlighter_opts:
    default_lang: plaintext
    block:
      line_numbers: false

optional_front_matter:
  remove_originals: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# include:
#   - markdown

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search: true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually: 1..6, default: 2
  heading_level: 2
  # Max amount of previews per search result, default: 3
  previews: 2
  # Max words to display before a matched word in the preview, default: 5
  preview_words_before: 3
  # Max words to display after a matched word in the preview, default: 10
  preview_words_after: 3
  # Set the search token separator, default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results, true (default) or false
  rel_url: true
  # Enable/disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
#aux_links:
#  "Just the Docs on GitHub":
#    - "//github.com/just-the-docs/just-the-docs"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

footer_content: "&nbsp;"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10
#ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)
